### DISCUSSION TITLE
How to execute pytest in a tox environment with the package being in the root directory?

### DISCUSSION THREAD

**Discussion by JackAshwell11** [pytest-dev/pytest#10582] [Q&A]
So if I have a directory structure like this:
```
proj/
├─ .tox/
├─ package/
│  ├─ source code here
├─ tests/
│  ├─ tests here
├─ pyproject.toml
```
And my pyproject.toml config:
```toml
[tool.pytest.ini_options]
addopts = "-vv -ra --showlocals --cov package --cov-report term-missing"
testpaths = ["tests"]

[tool.tox]
legacy_tox_ini = """
[tox]
envlist = py310
isolated_build = true

[testenv]
allowlist_externals = pytest
deps = pytest-cov
commands =
    python -I -m hades.extensions.compile
    pytest --cov-append
"""
```
Pytest is running the tests on the source code in package/ instead of the environment inside of .tox. I used to use the src/ directory structure, but since I'm adding Rust extensions, I can't use that anymore.

Is there a way I can get pytest to only run tests on the environments in .tox?
