### DISCUSSION TITLE
How to capture formatted logs

### DISCUSSION THREAD

**Discussion by M1s4k1** [pytest-dev/pytest#11649] [Q&A]
I'm using the standard logging.
a configuration file like this.
```
# logging_config.yml

version: 1

formatters:
  default:
    format: "processid : %(process)d, threadid : %(thread)d, time : %(asctime)s.%(msecs)03d, level : %(levelname)s	, msg : %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: default
  console2:
    class: logging.StreamHandler
    level: INFO
    formatter: default

loggers:
  packageName:
    handlers: [ console,console2]
    level: DEBUG
```
I used it by parsing the yaml file and calling the `logging.config.dictConfig()`.
I log info in my testcase
```
logger = logging.getLogger(__name__)
logger.info(f"{err_field}------:-------{err_dict}-")
```
The console outputs the formatted log and prints it twice as expected.But pytest captures the log output only once, and it's not formatted.How do I fix it.
I may need to use different filters,formatters,handlers for different modules
