### ISSUE TITLE
pytest on windows checks code snipets from docstrings

### ISSUE THREAD

**Issue by 5hv5hvnk** [pytest-dev/pytest#10292]
executing pytest on windows also checks the code snipets on doc strings and commented part. Running them on CI pipeline had fetch me this results multiple times. However, using Ubuntu 18.04 works fine and throws no such error on same piece of code. I believe this isn't the expected behaviour.
```
windows:
    strategy:
      matrix:
        os: [windows-latest]
        floatx: [float32, float64]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    env:
      TEST_SUBSET: ${{ matrix.test-subset }}
      AESARA_FLAGS: floatX=${{ matrix.floatx }},gcc__cxxflags='-march=core2'
    defaults:
      run:
        shell: cmd
```
test.yml for executing the pytest on CI pipeline
