### ISSUE TITLE
`capture` option in `ini_options`

### ISSUE THREAD

**Issue by silverwind** [pytest-dev/pytest#10952]
#### What's the problem this feature will solve?
I'd like to disable the capture feature per-project (equivalent of `-s`) in `pyproject.toml`. From what I can tell from the docs, this setting is only exposed on the CLI, not in the `ini_options`.

#### Describe the solution you'd like
```toml
[tool.pytest.ini_options]
capture = false
```

#### Alternative Solutions
none

#### Additional context
Currenlty such a config fails with `Unknown config option: capture`.

**Comment by nicoddemus** [comment]
Hi,

You can use `addopts` and pass `-p no:capture`.

```toml
[tool.pytest.ini_options]
addopts = "-p no:capture"
```
