### ISSUE TITLE
pdbcls as a configuration option?

### ISSUE THREAD

**Issue by paugier** [pytest-dev/pytest#12053]
#### What's the problem this feature will solve?

For some projects, I always use `--pdb` together with `--pdbcls=IPython.terminal.debugger:TerminalPdb`.  Unfortunately, `pytest --pdb --pdbcls=IPython.terminal.debugger:TerminalPdb` is a bit long and difficult to write. 

#### Describe the solution you'd like

I like to be able to write in a configuration file (in my case, pyproject.toml) that I prefer `IPython.terminal.debugger:TerminalPdb` so that I can just call `pytest --pdb` and use the IPython debugger.

Something like

```toml
[tool.pytest.ini_options]
pdbcls = "IPython.terminal.debugger:TerminalPdb"
```

It seems to me that it is currently not possible (https://docs.pytest.org/en/stable/reference/reference.html#ini-options-ref).
