### ISSUE TITLE
Adding shard option for distributing multiple nodes

### ISSUE THREAD

**Issue by daisuke834** [pytest-dev/pytest#12737]
#### What's the problem this feature will solve?

When we have many tests and thus CI takes a long time to be completed, it would be useful to split and distribute the tests to multiple nodes (instead of multiple processes within the same node).

For example with JS, it is easy to do it with shard option like this:
```
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shard: [1/4, 2/4, 3/4, 4/4]
  ..
  steps:
    ...
    - name: my test
      env:
        SHARD_OPTION: ${{ matrix.shard }}
      run: |
        yarn jest "--shard=${SHARD_OPTION}"
```

#### Describe the solution you'd like

So it would be very nice if `pytest` can have the shard option for doing like this:
```
jobs:
  test:
    runs-on: python:3.12
    strategy:
      matrix:
        shard: [1/4, 2/4, 3/4, 4/4]
  ..
  steps:
    ...
    - name: my test
      env:
        SHARD_OPTION: ${{ matrix.shard }}
      run: |
        pytest "--shard=${SHARD_OPTION}" .
```
Alghouth `pytest` has the plugin `pytest-xdist`, I don't think it has a feature for doing it.

#### Alternative Solutions

As a workaround, I have manually marked each test with `@pytest.mark` with hardcoded node number that the test is supposed to be executed at, but clearly it is not a good idea, and it isn't a scalable solution.
