### ISSUE TITLE
Inheritable pytest configuration

### ISSUE THREAD

**Issue by uwu-420** [pytest-dev/pytest#13173]
Hi, thanks for making pytest!

I'm trying out a monorepo setup which has a `pyproject.toml` file at the root level and one per sub-project in the monorepo. Ideally, I'd like to set something like
```toml
# ./pyproject.toml
[tool.pytest.ini_options]
asyncio_mode = "auto"
```
only once in the root-level `pyproject.toml` file and the sub-projects automatically inherits that setting unless overridden in their respective `pyproject.toml`. Another possibility would be to do it like ruff (see https://docs.astral.sh/ruff/settings/#extend). So something like this in the sub-project's `pyproject.toml`
```toml
# ./sub_project/pyproject.toml
[tool.pytest.ini_options]
extend = "../pyproject.toml"
# Inherits asyncio_mode = "auto"
addopts = "-v"
```
Cheers!
