### ISSUE TITLE
Test only specific files

### ISSUE THREAD

**Issue by ego-thales** [pytest-dev/pytest#13545]
Hi there,

I'm not sure this is a `pytest`  bug but  here it goes.

I have the following `pyproject.toml`  configuration
```toml
[tool.pytest.ini_options]
testpaths = "test"
addopts = [
    "--import-mode=importlib",  # Recommended by pytest
    "--cov",
]
```
so I can easily use
```bash
pytest
```
to start my tests.

Now when I want to test only a specific file, doing
```bash
pytest specific/file.py
```
ignores the argument, **while in the mean time**, passing another optional argument such as the following
```bash
pytest -s specific/file.py
```
works perfectly as intended.

Am I missing a piece or is this a pytest-side problem?

Thanks in advance!

All the best.
Élie
