### ISSUE TITLE
python_files option not recognised in pyproject.toml?

### ISSUE THREAD

**Issue by tgy** [pytest-dev/pytest#7399]
I am trying to set `python_files` to `"*.py"` (instead of the default `test_*.py *_test.py`) in my `pyproject.toml` file as follows
```toml
[tool.pytest.ini_options]
python_files = "*.py"
```
This does not work. What am I missing? I also tried setting it as `python_files = ["*.py"]`, to no avail.

```
❯ python --version
Python 3.8.2
```

```
❯ pytest --version
This is pytest version 5.4.1
```
