### ISSUE TITLE
tool.pytest.ini_options.markers in pyproject.toml not recognized

### ISSUE THREAD

**Issue by tomzx** [pytest-dev/pytest#7663]
Pytest: 6.0.1
Windows 7 x64 SP1

In my `pyproject.toml`, I have the following:

```toml

[tool.pytest.ini_options.markers]
requires_gpu = "mark a test that requires a GPU to run."
slow = "mark a test that takes a long time to run."

```

In my tests, I have marked a test with `@pytest.mark.requires_gpu`.

When I run `pytest -m "requires_gpu"`, only the marked tests are properly executed, as desired. However I also observe the following warnings:

```
PytestUnknownMarkWarning: Unknown pytest.mark.requires_gpu - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/mark.html
    @pytest.mark.requires_gpu
```

My expectations based on https://docs.pytest.org/en/stable/customize.html#pyproject-toml is that it is also possible to define `markers` within the `pyproject.toml` and that there is no need for a `pytest.ini`. In such case, those warnings should not be displayed.

**Comment by graingert** [comment]
Does it work with:

```toml
[tool.pytest.ini_options]
markers = [
    "requires_gpu = mark a test that requires a GPU to run.",
    "slow = mark a test that takes a long time to run.",
]
```
If so, this is still a bug as I'd expect your config to work
