### ISSUE TITLE
document how to handle minversion= in pyproject.toml

### ISSUE THREAD

**Issue by graingert** [pytest-dev/pytest#7730]
currently minversion `pyproject.toml[[tool.pytest.ini_options]minversion` doesn't apply when running on pytest<6 because those versions don't parse the file.

I've found a work-around using a `setup.cfg` because `pyproject.toml` takes priority over `setup.cfg`:

```toml
# pyproject.toml
[tool.pytest.ini_options]
minversion = "6.0"
```

```cfg
# setup.cfg
[tool:pytest]
minversion = 6
```

secondly it would be useful if `pyproject.toml` took priority over `pytest.ini` to allow pytest 4-6 to have  fowards-compatibility

see https://github.com/pytest-dev/pytest/issues/7653
