### ISSUE TITLE
proposal: Add a .pre-commit-hook.yaml to allow remote integration with pre-commit

### ISSUE THREAD

**Issue by deadpyxel** [pytest-dev/pytest#7794]
I think this would be useful since pytest in one of the most widely used testing libraries, and being able to just put it inside the pre-commit config would probably help even more people that want to use it to automate CI/CD workflows in their development cycle. Pytest uses `pyupgrade`, `black` and others as part of its pre-commit hooks, so I can't see a reason why pytest should not have something similar.

There're instruction on the [pre-commit docs](https://pre-commit.com/#new-hooks) about how to develop such integration, and I believe that since pytest has a lot of feature out of the box this would be viable.  

I would like to iterate on this if others think this could be nice addition, since I never did this kind of integration.

**Comment by deadpyxel** [comment]
For instance,  I think this could be a start:
```yaml
- id: pytest
  name: pytest
  description: pytest runs your test cases.
  entry: pytest
  language: python
  types: [python]
```
