### ISSUE TITLE
Configure --import-mode using pyproject.toml

### ISSUE THREAD

**Issue by Jasha10** [pytest-dev/pytest#9587]
#### What's the problem this feature will solve?
I'd like to localize my pytest settings in pyproject.toml.

How about an `import-mode` (or `import_mode` or `importmode`) setting in pyproject.toml?

**Comment by Jasha10** [comment]
I'm closing this issue as the desired behavior is possible with addopts:
```toml
[tool.pytest.ini_options]
addopts = "--import-mode=importlib"
```
